version: '3'

services:
  database:
    image: postgres
    environment:
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: carango_bom
      POSTGRES_USER: postgres
    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: natalia.winter@thoughtworks.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - 16543:80
    links:
      - database:pgsql-server