INSERT INTO BRANDS(NAME) VALUES ('VOLKSWAGEN');
INSERT INTO BRANDS(NAME) VALUES ('FIAT');
INSERT INTO BRANDS(NAME) VALUES ('RENAULT');
INSERT INTO BRANDS(NAME) VALUES ('HONDA');
INSERT INTO BRANDS(NAME) VALUES ('PEUGEOT');
INSERT INTO BRANDS(NAME) VALUES ('TOYOTA');
